package com.tqs.WebApp.Controller;

// Generated by Selenium IDE
import io.cucumber.java.en.And;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class getStatsForCountry {
    private WebDriver driver;

    @When("I navigate to {string}")
    public void iNavigateTo(String url) {
        driver = WebDriverManager.firefoxdriver().create();
        driver.get(url);
    }

    @And("I choose the country {string}")
    public void iChooseTheCountry(String country) {
        WebElement dropdown = driver.findElement(By.name("country"));
        dropdown.findElement(By.xpath("//option[. = '" + country + "']")).click();
        String value = driver.findElement(By.name("country")).getAttribute("value");
        assertThat(value, is(country));
    }

    @And("I click Submit")
    public void iClickSubmit() {
        driver.findElement(By.cssSelector(".btn")).click();
    }

    @Then("I should be see in the page body the pattern {string}")
    public void iShouldBeSeeInThePageBodyThePattern(String pattern) {
        try {
            assertThat(driver.findElement(By.cssSelector("html")).getText().replaceAll("[0-9-]","").replace("\n"," "), is(pattern));
        } catch (NoSuchElementException e) {
            throw new AssertionError(
                    "\"" + pattern + "\" not available in results");
        } finally {
            driver.quit();
        }
    }
}
